export enum IMAGE_BUTTON_ACTION {
  CLICK_IMAGE_BUTTON = "CLICK_IMAGE_BUTTON"
}

export enum MENU_DRAWER_ACTION {
  SHOW_MENU_DRAWER = "SHOW_MENU_DRAWER"
}

export enum ARROW_BUTTON_ACTION {
  REMOVE_ARROW_BUTTON = "REMOVE_ARROW_BUTTON",
  CHANGE_SELECTED_INDEX = "CHANGE_SELECTED_INDEX"
}
